### ISSUE TITLE
fix!: remove `Encrypter::Error` and panic on failure

### ISSUE THREAD

**Issue by WieeRd** [SkuldNorniern/cryptoPAN-rs#7]
# Rationale

### 1. AES is an algorithm, why would it ever *fail*?

RustCrypto implementation of block ciphers indeed does not fail.

- Returns `T` instead of `Result<T, E>`.
- No warnings about panics in the documentations as well.

### 2. `encrypt()` and `from_key()` should not share an error type

They are two separate process, and if they were to fail, they might fail in a whole different way.
Might even consider separating `from_key()` into its own trait `FromKey`.
Especially with the addition of `with_key(encrypter, padding)` in #6,
it will make it possible to use a cipher that is not initialized from a 128-bit key.

### 3. If so, when and why does OpenSSL return an `ErrorStack`?

Below are assumptions (needs confirmation via testing/research):

- Incompatible key or input length for a cipher
  - Never happens in our code, we guarantee the valid length
- Failed to find local OpenSSL installation
  - Is a valid reason to panic
  - But an error message instead of panic message would be nicer
 
## Tasks

- [ ] Confirm that those 2 are the only reason to return an `ErrorStack`
  - Investigate OpenSSL docs
  - Try running the tests in the environments without OpenSSL installed (Windows, esp.)
  - Try misdirecting the auto-detection via env vars
- [x] Find a way to detect the absence of OpenSSL early on
- [x] Remove `Encrypter::Error`

**Comment by WieeRd** [comment]
In addition to removing the error type, #8 somewhat addresses the 2nd task by exposing the internal `new()`.
(see the PR message for more context).
It is now up to you @SkuldNorniern for researching the cause of `ErrorStack`.

**Comment by SkuldNorniern** [comment]
What I can say about is, that OpenSSL is a piece of sh#t when it comes to Error related.
It seems like the Key Error is Mapped on the Rust binding side, which means most of the Errors coming from the incorrect key length are likely not generated at all. but still mapped the errors for the FFI 

and when we look at the code on 

- [openSSL FFI's return code wrapper](https://github.com/sfackler/rust-openssl/blob/450110f1bd00033545430f682e10ccc3c2e9677d/openssl/src/lib.rs#L221C1-L227C1)
- [openSSL's FFI caller wrapped in the upper context](https://github.com/sfackler/rust-openssl/blob/450110f1bd00033545430f682e10ccc3c2e9677d/openssl/src/cipher_ctx.rs#L592)

It will need further investigation for us to determine the cause of the errors that can caused from here LOL
